build: bani gard bomboane sala

bani: bani.cpp
	g++ -Wall bani.cpp -o bani

gard: gard.cpp
	g++ -Wall gard.cpp -o gard

bomboane: bomboane.cpp
	g++ -Wall bomboane.cpp -o bomboane

sala: sala.cpp
	g++ -Wall sala.cpp -o sala

run-p1: bani
	./bani

run-p2: gard
	./gard

run-p3: bomboane
	./bomboane

run-p4: sala
	./sala

clean:
	rm -f bani gard bomboane sala
